version: 2.1

parameters:
  ghcr_registry:
    type: string
    default: ghcr.io
  ghcr_username:
    type: string
    default: hikari-ai
  heroku_registry:
    type: string
    default: registry.heroku.com
  heroku_release_type:
    type: string
    default: web

  image:
    type: string
    default: jetson-packages-family
  tag:
    type: string
    default: latest

jobs:
  staging-build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: false
      - run:
          name: Login to Container Registries
          command: |
            docker login <<pipeline.parameters.ghcr_registry>> -u <<pipeline.parameters.ghcr_username>> -p $DOCKER_PASSWORD
            docker login <<pipeline.parameters.heroku_registry>> -u $HEROKU_USERNAME -p $HEROKU_TOKEN
      - run:
          name: Build and Tag Images
          command: |
            docker build -t base .
            docker tag base <<pipeline.parameters.ghcr_registry>>/<<pipeline.parameters.ghcr_username>>/<<pipeline.parameters.image>>:<<pipeline.parameters.tag>>
            docker tag base <<pipeline.parameters.heroku_registry>>/<<pipeline.parameters.image>>/<<pipeline.parameters.heroku_release_type>>
      - run:
          name: Push Images
          command: |
            docker push <<pipeline.parameters.ghcr_registry>>/<<pipeline.parameters.ghcr_username>>/<<pipeline.parameters.image>>:<<pipeline.parameters.tag>>
            docker push <<pipeline.parameters.heroku_registry>>/<<pipeline.parameters.image>>/<<pipeline.parameters.heroku_release_type>>

  staging-release:
    docker:
      - image: alpine
    steps:
      - run:
          name: Heroku Release
          command: |
            apk add curl bash nodejs
            curl https://cli-assets.heroku.com/install.sh | sh
            echo "machine api.heroku.com
              login $HEROKU_USERNAME
              password $HEROKU_TOKEN
            machine api.heroku.com
              login $HEROKU_USERNAME
              password $HEROKU_TOKEN
            " > ~/.netrc
            heroku container:release <<pipeline.parameters.heroku_release_type>> -a <<pipeline.parameters.image>>

workflows:
  staging-build-release:
    jobs:
      - staging-build-and-push:
          context: secrets
          filters:
            branches:
              only:
                - develop

      - staging-release:
          requires:
            - staging-build-and-push
          context: secrets

  # prod-build-release:
  #   jobs:
  #     - prod-build-and-push:
  #         context: secrets
  #         filters:
  #           branches:
  #             only:
  #               - master
  #
  #     - prod-release:
  #         requires:
  #           - prod-build-and-push
  #         context: secrets
