version: 2.1

parameters:
  registry:
    type: string
    default: ghcr.io
  username:
    type: string
    default: hikari-ai
  extra_build_args:
    type: string
    default: ""
  image:
    type: string
    default: jetson-packages-family
  tag:
    type: string
    default: latest

  ## build_all:
  ## build_dev:
  ## build_master:
jobs:
  build-and-push:
    ##    branches:
    ##      only:
    ##        - master
    ##        - hugo-docs
    machine: true
    steps:
      - checkout
      - run:
          command: echo "$DOCKER_PASSWORD" | docker login --username <<parameters.username>> --password-stdin
          name: login to GitHub Container Registry
      - run: 
          name: build image
          command: docker build -t <<parameters.registry>>/<<parameters.username>>/<<parameters.image>>:<<parameters.tag>>
      - run:
          name: publish image
          command: docker push <<parameters.registry>>/<<parameters.username>>/<<parameters.image>>:<<parameters.tag>>

workflows:
  build-and-publish-image:
    contexts:
      - secrets
    jobs:
      - build-and-push

  ##  build_all:
  ##    jobs:
  ##      - build_all:
  ##          filters:
  ##            branches:
  ##              ignore:
  ##                - develop
  ##                - master
  ##
  ##  build_dev:
  ##    jobs:
  ##      - build_dev:
  ##          filters:
  ##            branches:
  ##              only:
  ##                - develop
  ##
  ##  build_master:
  ##    jobs:
  ##      - build_master:
  ##          filters:
  ##            branches:
  ##              only:
  ##                - master
