version: 2.1

orbs:
  docker: circleci/docker@2.0.0

workflows:
  build-and-publish-image:
    jobs:
      - docker/publish:
          registry: ghcr.io
          image: hikari-ai/jetson-packages-family
          tag: latest
    contexts:
      - secrets
    branches:
      only:
        - master
        - hugo-docs
    environment:
      DOCKER_LOGIN: hikari-ai
