version: 2.1

parameters:
  registry:
    type: string
    default: ghcr.io
  username:
    type: string
    default: hikari-ai
  extra_build_args:
    type: string
    default: ""
  image:
    type: string
    default: jetson-packages-family
  tag:
    type: string
    default: latest

  ## build_all:
  ## build_dev:
  ## build_master:
jobs:
  build-and-push:
    ##    branches:
    ##      only:
    ##        - master
    ##        - hugo-docs
    machine: true
    steps:
      - checkout
      - run:
          name: Synchronize git submodule
          command: git submodule update --init --recursive
      - run:
          name: Login to GitHub Container Registry
          command: docker login ghcr.io --username <<pipeline.parameters.username>> -p $DOCKER_PASSWORD
      - run:
          name: Build image
          command: docker build -t <<pipeline.parameters.registry>>/<<pipeline.parameters.username>>/<<pipeline.parameters.image>>:<<pipeline.parameters.tag>> .
      - run:
          name: Publish image
          command: docker push <<pipeline.parameters.registry>>/<<pipeline.parameters.username>>/<<pipeline.parameters.image>>:<<pipeline.parameters.tag>>

workflows:
  build-and-publish-image:
    jobs:
      - build-and-push:
          context: secrets

  ##  build_all:
  ##    jobs:
  ##      - build_all:
  ##          filters:
  ##            branches:
  ##              ignore:
  ##                - develop
  ##                - master
  ##
  ##  build_dev:
  ##    jobs:
  ##      - build_dev:
  ##          filters:
  ##            branches:
  ##              only:
  ##                - develop
  ##
  ##  build_master:
  ##    jobs:
  ##      - build_master:
  ##          filters:
  ##            branches:
  ##              only:
  ##                - master
