version: 2.1

orbs:
  docker: circleci/docker@2.0.0

branches:
  only:
    - master
    - hugo-docs

contexts:
  - secrets

environment:
  DOCKER_LOGIN: hikari-ai
  DOCKER_PASSWORD: $DOCKER_PASSWORD

workflows:
  build-and-publish-image:
    jobs:
      - docker/publish:
          registry: ghcr.io
          image: hikari-ai/jetson-packages-family
          tag: latest
