# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  kaniko-publish: glenjamin/kaniko-publish@0.0.1

parameters:
  registry:
    type: string
    default: ghcr.io
  extra_build_args:
    type: string
    default: ''
  image:
    type: string
    default: hikari-ai/jetson-packages-family
  tag:
    type: string
    default: latest

jobs:
  kaniko-build-and-publish:
    branches:
      only:
        - master
        - hugo-docs
  steps:
    - kaniko-publish/build_and_push



  ## build_all:
  ## build_dev:
  ## build_master:

workflows:
  build-and-publish:
    jobs:
      - kaniko-build-and-push

  ##  build_all:
  ##    jobs:
  ##      - build_all:
  ##          filters:
  ##            branches:
  ##              ignore:
  ##                - develop
  ##                - master
  ##
  ##  build_dev:
  ##    jobs:
  ##      - build_dev:
  ##          filters:
  ##            branches:
  ##              only:
  ##                - develop
  ##
  ##  build_master:
  ##    jobs:
  ##      - build_master:
  ##          filters:
  ##            branches:
  ##              only:
  ##                - master
