version: 2.1
orbs:
  docker: circleci/docker@2.0.0

workflows:
  build-and-publish:
    jobs:
      - docker/publish:
        image: hikari-ai/jetson-packages-family
        tag: latest
    branches:
      only:
        - master
        - hugo-docs
    contexts:
      - secrets
