version: 2.1

branches:
  only:
    - master
    - hugo-docs

contexts:
  - secrets

environment:
  DOCKER_LOGIN: hikari-ai

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login ghcr.io -u $DOCKER_LOGIN --password-stdin
      - run: docker build -t hikari-ai/jetson-packages-family .
      - run: docker push hikari-ai/jetson-packages-family
