baseURL = "https://example.com/"
title = "Compose Docs"
theme = "compose"
enableRobotsTXT = true
enableGitInfo = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML", "RSS", "JSON"]
