baseURL = "https://example.com/"
title = "Compose Docs"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML", "RSS", "JSON"]
